version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 2
    commit-message:
      prefix: chore
      prefix-development: chore
      include: scope
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    commit-message:
      prefix: chore
      prefix-development: chore
      include: scope
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 2
    commit-message:
      prefix: chore
      prefix-development: chore
      include: scope
